### ISSUE TITLE
OOM on Ubuntu 14.04 with GTX670

### ISSUE THREAD

**Issue by JoeyTeng** [dennybritz/chatbot-retrieval#11]
Hi,

I tried to run the demo with GPU, and it raised an error at Step 68001 suddenly. 

I tried to run this on my Macbook Pro with 'CPU only' version, and there was no error over 70000 steps. I believe this error is due to the small memory of the GPU. Is there any way to fix this problem?

Last part of the Log (excluding the memory part):
```
InUse:                  1890070528
MaxInUse:               1890070528
NumAllocs:              1307072597
MaxAllocSize:             73287680

W tensorflow/core/common_runtime/bfc_allocator.cc:270] ****************************************************************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:271] Ran out of memory trying to allocate 1.00MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:909] Resource exhausted: OOM when allocating tensor with shape[256,1024]
INFO:tensorflow:Saving checkpoint for step 68001 to checkpoint: /home/harmanjohll/SaveTheDepressed/chatbot-retrieval/runs/1471341127/model.ckpt.
Traceback (most recent call last):
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 715, in _do_call
    return fn(*args)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 697, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.4/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/framework/errors.py", line 450, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.ResourceExhaustedError: OOM when allocating tensor with shape[256,1024]
	 [[Node: rnn/RNN/while/LSTMCell/BiasAdd = BiasAdd[T=DT_FLOAT, data_format="NHWC", _device="/job:localhost/replica:0/task:0/gpu:0"](rnn/RNN/while/LSTMCell/MatMul, rnn/RNN/while/LSTMCell/BiasAdd/Enter)]]
	 [[Node: OptimizeLoss/train/update/_201717 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1043_OptimizeLoss/train/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "udc_train.py", line 70, in <module>
    tf.app.run()
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "udc_train.py", line 67, in main
    estimator.fit(input_fn=input_fn_train, steps=None, monitors=[eval_monitor])
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 182, in fit
    monitors=monitors)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 484, in _train_model
    monitors=monitors)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/contrib/learn/python/learn/graph_actions.py", line 328, in train
    reraise(*excinfo)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/six.py", line 686, in reraise
    raise value
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/contrib/learn/python/learn/graph_actions.py", line 257, in train
    session, last_step + 1, [train_op, loss_op], feed_dict, monitors)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/contrib/learn/python/learn/graph_actions.py", line 111, in _run_with_monitors
    outputs = session.run(tensors, feed_dict=feed_dict)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 636, in _run
    feed_dict_string, options, run_metadata)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 708, in _do_run
    target_list, options, run_metadata)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 728, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.ResourceExhaustedError: OOM when allocating tensor with shape[256,1024]
	 [[Node: rnn/RNN/while/LSTMCell/BiasAdd = BiasAdd[T=DT_FLOAT, data_format="NHWC", _device="/job:localhost/replica:0/task:0/gpu:0"](rnn/RNN/while/LSTMCell/MatMul, rnn/RNN/while/LSTMCell/BiasAdd/Enter)]]
	 [[Node: OptimizeLoss/train/update/_201717 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1043_OptimizeLoss/train/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Caused by op 'rnn/RNN/while/LSTMCell/BiasAdd', defined at:
  File "udc_train.py", line 70, in <module>
    tf.app.run()
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "udc_train.py", line 67, in main
    estimator.fit(input_fn=input_fn_train, steps=None, monitors=[eval_monitor])
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 182, in fit
    monitors=monitors)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 449, in _train_model
    train_op, loss_op = self._get_train_ops(features, targets)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 673, in _get_train_ops
    _, loss, train_op = self._call_model_fn(features, targets, ModeKeys.TRAIN)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 656, in _call_model_fn
    features, targets, mode=mode)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/udc_model.py", line 40, in model_fn
    targets)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/models/dual_encoder.py", line 56, in dual_encoder_model
    dtype=tf.float32)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/ops/rnn.py", line 580, in dynamic_rnn
    swap_memory=swap_memory, sequence_length=sequence_length)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/ops/rnn.py", line 709, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1873, in while_loop
    result = context.BuildLoop(cond, body, loop_vars)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1749, in BuildLoop
    body_result = body(*vars_for_body_with_tensor_arrays)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/ops/rnn.py", line 692, in _time_step
    skip_conditionals=True)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/ops/rnn.py", line 326, in _rnn_step
    new_output, new_state = call_cell()
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/ops/rnn.py", line 680, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/ops/rnn_cell.py", line 552, in __call__
    lstm_matrix = nn_ops.bias_add(math_ops.matmul(cell_inputs, concat_w), b)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/ops/nn_ops.py", line 313, in bias_add
    return gen_nn_ops._bias_add(value, bias, data_format=data_format, name=name)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 279, in _bias_add
    data_format=data_format, name=name)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 2260, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/harmanjohll/SaveTheDepressed/chatbot-retrieval/venv/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 1230, in __init__
    self._traceback = _extract_stack()

```

By the way, will udc_train.py automatically resume training from the checkpoint? And do I need to process all the training data?

**Comment by dennybritz** [comment]
If your OOM you may need to make the model parameters smaller (see https://github.com/dennybritz/chatbot-retrieval/blob/master/udc_hparams.py).

It will resume training if you set the `model_dir` parameter to where it saved the model previously (see code in train.y).

**Comment by JoeyTeng** [comment]
Is there anyway to reduce the usage of GPU memory but instead, save some data in memory such that I can train a big model with limited GPU memory?

And anyway, thanks:)

**Comment by dennybritz** [comment]
Try training with a smaller batch size (also in hparams). That means you matrix multiplications are smaller and need less memory.

**Comment by JoeyTeng** [comment]
Oh, I see... I wonder why OOM occur only after certain steps of calculation? Does the GPU memory save all the previous batches of data? Or to be specific, what are the data saved in GPU memory:)

**Comment by dennybritz** [comment]
I'm not sure. It could be related to the sequence length of the examples. E.g. if you have a really long sentence and the RNN needs to backpropagate through it you may run out of memory for that examples.
