### ISSUE TITLE
(udc_test.py) Incompatible shapes: [80,1] vs. [160,1] error even after changing the batch size 

### ISSUE THREAD

**Issue by rguptabinary** [dennybritz/chatbot-retrieval#32]
Getting the below error, please help.

`INFO:tensorflow:Results after 1180 steps (0.934 sec/batch): loss = 0.493843, recall_at_1 = 0.399258474576, recall_at_10 = 1.0, recall_at_2 = 0.592213983051, recall_at_5 = 0.868485169492.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [80,1] vs. [160,1]
	 [[Node: prediction/logistic_loss/mul = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](prediction/Squeeze, prediction/ToFloat)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "udc_test.py", line 39, in <module>
    estimator.evaluate(input_fn=input_fn_test, steps=None, metrics=eval_metrics)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 247, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 436, in evaluate
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 816, in _evaluate_model
    max_steps=steps)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/graph_actions.py", line 754, in evaluate
    session.run(update_op, feed_dict=feed_dict)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [80,1] vs. [160,1]
	 [[Node: prediction/logistic_loss/mul = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](prediction/Squeeze, prediction/ToFloat)]]

Caused by op 'prediction/logistic_loss/mul', defined at:
  File "udc_test.py", line 39, in <module>
    estimator.evaluate(input_fn=input_fn_test, steps=None, metrics=eval_metrics)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 247, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 436, in evaluate
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 800, in _evaluate_model
    eval_ops = self._get_eval_ops(features, labels, metrics)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1106, in _get_eval_ops
    features, labels, model_fn_lib.ModeKeys.EVAL)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1047, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, mode=mode)
  File "/home/rohitg/Documents/chatbot-retrieval-master/udc_model.py", line 83, in model_fn
    tf.concat(0, all_targets))
  File "/home/rohitg/Documents/chatbot-retrieval-master/models/dual_encoder.py", line 81, in dual_encoder_model
    losses = tf.nn.sigmoid_cross_entropy_with_logits(logits, tf.to_float(targets))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_impl.py", line 162, in sigmoid_cross_entropy_with_logits
    return math_ops.add(relu_logits - logits * targets,
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 816, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 1037, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 1613, in mul
    result = _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2371, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1258, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Incompatible shapes: [80,1] vs. [160,1]
	 [[Node: prediction/logistic_loss/mul = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](prediction/Squeeze, prediction/ToFloat)]]
`

**Comment by Sangheli** [comment]
for **udc_test.py** you can set **test_batch_size** to _8_, as a **batch_size** in **udc_hparams.py**
https://github.com/dennybritz/chatbot-retrieval/blob/master/udc_test.py#L15

**Comment by rguptabinary** [comment]
Sangheli thanks, it worked, but now while running udc_predict.py am getting error
`  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1047, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, mode=mode)
  File "/home/rohitg/Documents/chatbot-retrieval-master/udc_model.py", line 29, in model_fn
    batch_size = targets.get_shape().as_list()[0]
AttributeError: 'dict' object has no attribute 'get_shape'
`

**Comment by Sangheli** [comment]
wich version of tensorflow you use? in tensorflow 0.11 all works correct (python 3.5)

**Comment by rguptabinary** [comment]
The version am using is 0.12.0 and python 3.5

**Comment by Sangheli** [comment]
i have some problems while running this code in tf 0.12 or 0.10

**Comment by rguptabinary** [comment]
Do I need to switch to .11?

**Comment by Sangheli** [comment]
yes, this helped me

**Comment by rguptabinary** [comment]
Do I need to train data again or I can use the same output data there?

**Comment by Sangheli** [comment]
I don't know, I'm trained every time  I trying to solve problems, on gt 770 4gb train time about 1-2 hours(16 000 steps), to get perfect results on ubuntu text corpus, in other issues author says he train 2000 steps, to get good result

**Comment by rguptabinary** [comment]
Thanks for helping me out :D

**Comment by rguptabinary** [comment]
Cool it worked with .11, I wonder what is the prob with .12

**Comment by basma-b** [comment]
@Sangheli please I am getting the same error on training, should I change batch_size or eval_batch_size in udc_hparams.py to 8 and test_batch_size in udc_test.py to 8 too ?

**Comment by jugador** [comment]
In my case I changed both.
**In udc_hparams.py**
`tf.flags.DEFINE_integer("batch_size", 64, "Batch size during training")
tf.flags.DEFINE_integer("eval_batch_size", 8, "Batch size during evaluation")`
**In udc_test.py**
`tf.flags.DEFINE_integer("test_batch_size", 8, "Batch size for testing")`

After that it  started working. I had to rerun the train script. Also I changed my tf to version .11

**Comment by Sangheli** [comment]
if move 

> batch_size = targets.get_shape().as_list()[0]

to

> if mode == tf.contrib.learn.ModeKeys.EVAL:
> _____batch_size = targets.get_shape().as_list()[0]

code work correctly on **tf 0.12** in predict mode, but you need change call of predict function, as in example https://github.com/Sangheli/chatbot-retrieval/blob/master/udc_predict.py#L68
without flag **as_iterable**

**Comment by hunkim** [comment]
Can any of you make a pull request to fix this issue?

**Comment by yogesh-0586** [comment]
udc_predict.py return only `POTENTIAL_RESPONSES` zero position value
