### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_shape'

### ISSUE THREAD

**Issue by prithajnath** [dennybritz/chatbot-retrieval#33]
When I try to run `python3 udc_predict.py --model_dir=runs/1481407347`, I get the following error

Context: Example context
Traceback (most recent call last):
  File "udc_predict.py", line 57, in <module>
    prob = estimator.predict(input_fn=lambda: get_features(INPUT_CONTEXT, r))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/python/util/deprecation.py", line 191, in new_func
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 469, in predict
    as_iterable=as_iterable)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 839, in _infer_model
    infer_ops = self._get_predict_ops(features)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1107, in _get_predict_ops
    return self._call_model_fn(features, labels, model_fn_lib.ModeKeys.INFER)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1021, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, mode=mode)
  File "/home/ubuntu/neural_net/chatbot-retrieval/udc_model.py", line 29, in model_fn
    batch_size = targets.get_shape().as_list()[0]
AttributeError: 'NoneType' object has no attribute 'get_shape'

Any ideas what might be causing this? Thanks!

**Comment by Sangheli** [comment]
try this variant: https://github.com/dennybritz/chatbot-retrieval/issues/32#issuecomment-265819109

**Comment by KristenMoore** [comment]
Thanks, @Sangheli - your fix is very helpful.
