### ISSUE TITLE
No module named 'tensorflow.contrib.learn.python.learn.metric_spec

### ISSUE THREAD

**Issue by supradeepk** [dennybritz/chatbot-retrieval#42]
I am using tensorflow 0.10 and python 3.5 and getting following error while running udc_train.py

    Traceback (most recent call last):
    File "udc_train.py", line 7, in <module>
    import udc_metrics
    File "/home/sudeep/git_hub/chatbot-retrieval/udc_metrics.py", line 3, in <module>
    from tensorflow.contrib.learn.python.learn.metric_spec import MetricSpec
    ImportError: No module named 'tensorflow.contrib.learn.python.learn.metric_spec'

**Comment by jimmytuc** [comment]
I has updated my tensorflow version to 0.12, that error gone away but cannot train! The console display "Killed" when run `python udc_train.py`

Python: 3.5.2 Anaconda 4.2.0 64 bit
Tensorflow: 0.12

**Comment by SeekPoint** [comment]
yes! it raised on tf0.9
however, update to tf0.10 will got another error
