### ISSUE TITLE
TypeError: object() takes no parameters

### ISSUE THREAD

**Issue by akhilgollapudi** [dennybritz/chatbot-retrieval#50]
Hi,
while  I am trying to execute udc_train.py, I am facing this issue,can anyone suggest me to solve this issue.
Thanks :)

INFO:tensorflow:Using config: {'_save_summary_steps': 100, '_task_id': 0, '_save_checkpoints_secs': 600, '_evaluation_master': '', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_keep_checkpoint_every_n_hours': 10000, '_master': '', '_is_chief': True, '_environment': 'local', '_num_ps_replicas': 0, '_keep_checkpoint_max': 5, '_model_dir': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fe3298dd7b8>, '_task_type': None, '_tf_random_seed': None, '_num_worker_replicas': 0, '_save_checkpoints_steps': None}
Traceback (most recent call last):
  File "udc_train.py", line 66, in <module>
    tf.app.run() 
  File "/home/akhil_gollapudi5/ex/envname/lib/python3.4/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "udc_train.py", line 60, in main
    metrics=eval_metrics)
TypeError: object() takes no parameters

**Comment by razaazem** [comment]
/usr/bin/python3.6 /root/PycharmProjects/TkInter/account.py
Traceback (most recent call last):
  File "/root/PycharmProjects/TkInter/account.py", line 20, in <module>
    Azeem = Account("Azeem", 0)
TypeError: object() takes no parameters

Process finished with exit code 1
