### ISSUE TITLE
ValueError: No files match ['/home/gopinathankm/ChatBots/chatbot-retrieval-master/data/train.tfrecords']

### ISSUE THREAD

**Issue by gopinathankm** [dennybritz/chatbot-retrieval#64]
Upon running python udc_train.py getting following error even though data file is properly extracted 
(my_env36) gopinathankm@gopinathankm-Lenovo-G400 ~/ChatBots/chatbot-retrieval-master $ python udc_train.py
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f819861f358>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/home/gopinathankm/ChatBots/chatbot-retrieval-master/runs/1521450147'}
WARNING:tensorflow:From /home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:269: BaseMonitor.__init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
Traceback (most recent call last):
  File "udc_train.py", line 64, in <module>
    tf.app.run()
  File "/home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "udc_train.py", line 61, in main
    estimator.fit(input_fn=input_fn_train, steps=None, monitors=[eval_monitor])
  File "/home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "/home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 458, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 956, in _train_model
    features, labels = input_fn()
  File "/home/gopinathankm/ChatBots/chatbot-retrieval-master/udc_inputs.py", line 46, in input_fn
    name="read_batch_features_{}".format(mode))
  File "/home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/graph_io.py", line 790, in read_batch_features
    name=name)
  File "/home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/graph_io.py", line 506, in read_keyed_batch_features
    name=scope)
  File "/home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/graph_io.py", line 174, in read_keyed_batch_examples
    seed=seed)
  File "/home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/graph_io.py", line 357, in _read_keyed_batch_examples_helper
    file_names = _get_file_names(file_pattern, randomize_input)
  File "/home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/graph_io.py", line 272, in _get_file_names
    raise ValueError('No files match %s.' % file_pattern)
ValueError: No files match ['/home/gopinathankm/ChatBots/chatbot-retrieval-master/data/train.tfrecords'].
(my_env36) gopinathankm@gopinathankm-Lenovo-G400 ~/ChatBots/chatbot-retrieval-master $ python udc_train.py
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fc017d582b0>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_log_step_count_steps': 100, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/home/gopinathankm/ChatBots/chatbot-retrieval-master/runs/1521450608'}
WARNING:tensorflow:From /home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:269: BaseMonitor.__init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
Traceback (most recent call last):
  File "udc_train.py", line 64, in <module>
    tf.app.run()
  File "/home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "udc_train.py", line 61, in main
    estimator.fit(input_fn=input_fn_train, steps=None, monitors=[eval_monitor])
  File "/home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 296, in new_func
    return func(*args, **kwargs)
  File "/home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 458, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "/home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 956, in _train_model
    features, labels = input_fn()
  File "/home/gopinathankm/ChatBots/chatbot-retrieval-master/udc_inputs.py", line 46, in input_fn
    name="read_batch_features_{}".format(mode))
  File "/home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/graph_io.py", line 790, in read_batch_features
    name=name)
  File "/home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/graph_io.py", line 506, in read_keyed_batch_features
    name=scope)
  File "/home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/graph_io.py", line 174, in read_keyed_batch_examples
    seed=seed)
  File "/home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/graph_io.py", line 357, in _read_keyed_batch_examples_helper
    file_names = _get_file_names(file_pattern, randomize_input)
  File "/home/gopinathankm/anaconda3/envs/my_env36/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_io/graph_io.py", line 272, in _get_file_names
    raise ValueError('No files match %s.' % file_pattern)
ValueError: No files match ['/home/gopinathankm/ChatBots/chatbot-retrieval-master/data/train.tfrecords'].

**Comment by gopinathankm** [comment]
Issue is closed. It because of directory structure error. Thanks

**Comment by rahuls321** [comment]
Before running udc_train.py first run prepare_data.py with data directory in the home folder.
