### ISSUE TITLE
Something wrong with the udc_metrics.py

### ISSUE THREAD

**Issue by fj2889** [dennybritz/chatbot-retrieval#65]
ERROR:tensorflow:Could not create metric ops for MetricSpec(metric_fn=streaming_sparse_recall_at_k, prediction_key=None, label_key=None, weight_key=None), input must have last dimension >= k = 10 but is 1 for 'recall_at_10/TopKV2' (op: 'TopKV2') with input shapes: [?,1], [] and with computed input tensors: input[1] = <10>..

Traceback (most recent call last):
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: input must have last dimension >= k = 10 but is 1 for 'recall_at_10/TopKV2' (op: 'TopKV2') with input shapes: [?,1], [] and with computed input tensors: input[1] = <10>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/Graduation_Project/chatbot-retrieval/udc_train.py", line 64, in <module>
    tf.app.run()
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "E:/Graduation_Project/chatbot-retrieval/udc_train.py", line 61, in main
    estimator.fit(input_fn=input_fn_train, steps=None, monitors=[eval_monitor])
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\util\deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 497, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1067, in _train_model
    _, loss = mon_sess.run([model_fn_ops.train_op, model_fn_ops.loss])
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\training\monitored_session.py", line 546, in run
    run_metadata=run_metadata)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1022, in run
    run_metadata=run_metadata)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1113, in run
    raise six.reraise(*original_exc_info)
  File "E:\Anaconda\anaconda\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1098, in run
    return self._sess.run(*args, **kwargs)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1178, in run
    run_metadata=run_metadata))
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\contrib\learn\python\learn\monitors.py", line 1220, in after_run
    induce_stop = m.step_end(self._last_step, result)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\contrib\learn\python\learn\monitors.py", line 356, in step_end
    return self.every_n_step_end(step, output)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\contrib\learn\python\learn\monitors.py", line 708, in every_n_step_end
    validation_outputs = self._evaluate_estimator()
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\contrib\learn\python\learn\monitors.py", line 684, in _evaluate_estimator
    name=self.name)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\util\deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 590, in evaluate
    log_progress=log_progress)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 883, in _evaluate_model
    model_fn_results = self._get_eval_ops(features, labels, metrics)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1257, in _get_eval_ops
    model_fn_lib.ModeKeys.EVAL, metrics)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 1211, in _call_model_fn
    model_fn_ops.predictions))
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\estimator.py", line 274, in _make_metrics_ops
    result[name] = metric.create_metric_ops(features, labels, predictions)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\contrib\learn\python\learn\metric_spec.py", line 428, in create_metric_ops
    weights=inputs[self.weight_key] if self.weight_key else None)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\contrib\learn\python\learn\metric_spec.py", line 164, in _named_metric_fn
    return metric_fn(**kwargs)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\contrib\metrics\python\ops\metric_ops.py", line 1924, in streaming_sparse_recall_at_k
    name=name)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\ops\metrics_impl.py", line 2414, in recall_at_k
    _, top_k_idx = nn.top_k(predictions, k)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 2308, in top_k
    return gen_nn_ops._top_kv2(input, k=k, sorted=sorted, name=name)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 5438, in _top_kv2
    "TopKV2", input=input, k=k, sorted=sorted, name=name)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 3273, in create_op
    compute_device=compute_device)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 3313, in _create_op_helper
    set_shapes_for_outputs(op)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 2501, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 2474, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\framework\ops.py", line 2404, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "E:\Anaconda\anaconda\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: input must have last dimension >= k = 10 but is 1 for 'recall_at_10/TopKV2' (op: 'TopKV2') with input shapes: [?,1], [] and with computed input tensors: input[1] = <10>.

**Comment by fj2889** [comment]
Sorry, it's my fault. When I change the `shaped_probs = tf.concat(split_probs, 1)` in udc_model.py, I write 0 in the `tf.concat`. That's why my program has the problem with dimensions.
