### ISSUE TITLE
Gettin error while running idc_train.py 

### ISSUE THREAD

**Issue by thombrey-vinil** [dennybritz/chatbot-retrieval#71]
Error:

INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0xd27c57c88>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1.0
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': None}
WARNING:tensorflow:From /Users/vinilthombrey/anaconda/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/monitors.py:267: BaseMonitor.__init__ (from tensorflow.contrib.learn.python.learn.monitors) is deprecated and will be removed after 2016-12-05.
Instructions for updating:
Monitors are deprecated. Please use tf.train.SessionRunHook.
INFO:tensorflow:No glove/vocab path specificed, starting with random embeddings.
Traceback (most recent call last):

  File "<ipython-input-1-f995184a8ad4>", line 1, in <module>
    runfile('/Users/vinilthombrey/Downloads/chatbot-retrieval-master/udc_train.py', wdir='/Users/vinilthombrey/Downloads/chatbot-retrieval-master')

  File "/Users/vinilthombrey/anaconda/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/Users/vinilthombrey/anaconda/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/vinilthombrey/Downloads/chatbot-retrieval-master/udc_train.py", line 64, in <module>
    tf.app.run()

  File "/Users/vinilthombrey/anaconda/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))

  File "/Users/vinilthombrey/Downloads/chatbot-retrieval-master/udc_train.py", line 61, in main
    estimator.fit(input_fn=input_fn_train, steps=None, monitors=[eval_monitor])

  File "/Users/vinilthombrey/anaconda/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 281, in new_func
    return func(*args, **kwargs)

  File "/Users/vinilthombrey/anaconda/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 430, in fit
    loss = self._train_model(input_fn=input_fn, hooks=hooks)

  File "/Users/vinilthombrey/anaconda/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 927, in _train_model
    model_fn_ops = self._get_train_ops(features, labels)

  File "/Users/vinilthombrey/anaconda/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1132, in _get_train_ops
    return self._call_model_fn(features, labels, model_fn_lib.ModeKeys.TRAIN)

  File "/Users/vinilthombrey/anaconda/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1103, in _call_model_fn
    model_fn_results = self._model_fn(features, labels, **kwargs)

  File "/Users/vinilthombrey/Downloads/chatbot-retrieval-master/udc_model.py", line 39, in model_fn
    targets)

  File "/Users/vinilthombrey/Downloads/chatbot-retrieval-master/models/dual_encoder.py", line 54, in dual_encoder_model
    tf.concat(0, [context_embedded, utterance_embedded]),

  File "/Users/vinilthombrey/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(

  File "/Users/vinilthombrey/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 639, in convert_to_tensor
    as_ref=False)

  File "/Users/vinilthombrey/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 704, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)

  File "/Users/vinilthombrey/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)

  File "/Users/vinilthombrey/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))

  File "/Users/vinilthombrey/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 370, in make_tensor_proto
    _AssertCompatible(values, dtype)

  File "/Users/vinilthombrey/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))

**TypeError: Expected int32, got list containing Tensors of type '_Message' instead.**

**Comment by amycardoso** [comment]
Same error, did you found a solution @thombrey-vinil ?

**Comment by nidhikamath91** [comment]
Changing tf.concat(0, [context_embedded, utterance_embedded]) to tf.concat([context_embedded, utterance_embedded], 0) resolved the issue

**Comment by seaweiqing** [comment]
This should be counted as one of the errors caused by different version of tensorflow
